jobs:
  create-cache:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      uses: Nfsaavedra/workflow-telemetry-action@raw_data
      with:
        save_raw_stats: true
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
      with:
        node-version: '20'
    - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
    - id: pnpm-cache
      name: Get pnpm cache info
      run: 'echo "store=$(pnpm store path)" >> $GITHUB_OUTPUT

        echo "date=$(/bin/date -u "+%Y-%m-%d")" >> $GITHUB_OUTPUT

        '
    - name: pnpm install
      run: pnpm install
    - name: Save pnpm cache
      uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
      with:
        key: ${{ runner.os }}-pnpm-store-cache-${{ steps.pnpm-cache.outputs.date }}
        path: ${{ steps.pnpm-cache.outputs.store }}
name: pnpm cache
'on':
- workflow_dispatch
permissions: write-all
