jobs:
  create-cache:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      uses: Nfsaavedra/workflow-telemetry-action@raw_data
      with:
        save_raw_stats: true
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
      with:
        node-version: '20'
    - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598
    - id: pnpm-cache
      name: Get pnpm cache info
      run: 'echo "store=$(pnpm store path)" >> $GITHUB_OUTPUT

        echo "date=$(/bin/date -u "+%Y-%m-%d")" >> $GITHUB_OUTPUT

        '
    - name: pnpm install
      run: pnpm install
    - name: Save pnpm cache
      uses: actions/cache/save@e12d46a63a90f2fae62d114769bbf2a179198b5c
      with:
        key: ${{ runner.os }}-pnpm-store-cache-${{ steps.pnpm-cache.outputs.date }}
        path: ${{ steps.pnpm-cache.outputs.store }}
name: pnpm cache
'on':
- workflow_dispatch
permissions: write-all
