jobs:
  create-cache:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      uses: Nfsaavedra/workflow-telemetry-action@raw_data
      with:
        save_raw_stats: true
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
      with:
        node-version: '20'
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
    - id: pnpm-cache
      name: Get pnpm cache info
      run: 'echo "store=$(pnpm store path)" >> $GITHUB_OUTPUT

        echo "date=$(/bin/date -u "+%Y-%m-%d")" >> $GITHUB_OUTPUT

        '
    - name: pnpm install
      run: pnpm install
    - name: Save pnpm cache
      uses: actions/cache/save@0c907a75c2c80ebcb7f088228285e798b750cf8f
      with:
        key: ${{ runner.os }}-pnpm-store-cache-${{ steps.pnpm-cache.outputs.date }}
        path: ${{ steps.pnpm-cache.outputs.store }}
name: pnpm cache
'on':
- workflow_dispatch
permissions: write-all
